import { Card, RawCard } from "./types";

const items: Array<RawCard> = [
  {
    name: "Dave",
    phonenum: "555-1111",
    hangout: "Crosstown Mall",
    sport: "null",
    food: "Cookies",
    clothing: "Blue Jeans",
  },
  {
    name: "George",
    phonenum: "555-1233",
    hangout: "Crosstown Mall",
    sport: "null",
    food: "Ice Cream",
    clothing: "Tie",
  },
  {
    name: "Dale",
    phonenum: "555-4566",
    hangout: "Crosstown Mall",
    sport: "null",
    food: "Ice Cream",
    clothing: "Jacket",
  },
  {
    name: "Alan",
    phonenum: "555-7899",
    hangout: "Crosstown Mall",
    sport: "null",
    food: "Cookies",
    clothing: "Tie",
  },
  {
    name: "James",
    phonenum: "555-2588",
    hangout: "E.A.T.S. Snack Shop",
    sport: "null",
    food: "Hot Dogs",
    clothing: "Jacket",
  },
  {
    name: "Phil",
    phonenum: "555-3333",
    hangout: "E.A.T.S. Snack Shop",
    sport: "null",
    food: "Pizza",
    clothing: "Glasses",
  },
  {
    name: "Bruce",
    phonenum: "555-3699",
    hangout: "E.A.T.S. Snack Shop",
    sport: "null",
    food: "Pizza",
    clothing: "Tie",
  },
  {
    name: "Tyler",
    phonenum: "555-1477",
    hangout: "E.A.T.S. Snack Shop",
    sport: "null",
    food: "Hot Dogs",
    clothing: "Blue Jeans",
  },
  {
    name: "Jamal",
    phonenum: "555-9877",
    hangout: "Reel Movies",
    sport: "null",
    food: "Candy",
    clothing: "Tie",
  },
  {
    name: "Gary",
    phonenum: "555-3211",
    hangout: "Reel Movies",
    sport: "null",
    food: "Popcorn",
    clothing: "Blue Jeans",
  },
  {
    name: "Dan",
    phonenum: "555-7777",
    hangout: "Reel Movies",
    sport: "null",
    food: "Candy",
    clothing: "Blue Jeans",
  },
  {
    name: "Spencer",
    phonenum: "555-6544",
    hangout: "Reel Movies",
    sport: "null",
    food: "Popcorn",
    clothing: "Jacket",
  },
  {
    name: "Mark",
    phonenum: "555-8522",
    hangout: "Woodland Park",
    sport: "Baseball",
    food: "null",
    clothing: "Hat",
  },
  {
    name: "Jason",
    phonenum: "555-7411",
    hangout: "Woodland Park",
    sport: "Baseball",
    food: "null",
    clothing: "Glasses",
  },
  {
    name: "Steve",
    phonenum: "555-9999",
    hangout: "Woodland Park",
    sport: "Skateboarding",
    food: "null",
    clothing: "Jacket",
  },
  {
    name: "John",
    phonenum: "555-9633",
    hangout: "Woodland Park",
    sport: "Skateboarding",
    food: "null",
    clothing: "Anything Yellow",
  },
  {
    name: "Paul",
    phonenum: "555-5515",
    hangout: "High Tide Beach",
    sport: "Volleyball",
    food: "null",
    clothing: "Anything Yellow",
  },
  {
    name: "Tony",
    phonenum: "555-2442",
    hangout: "High Tide Beach",
    sport: "Volleyball",
    food: "null",
    clothing: "Hat",
  },
  {
    name: "Wayne",
    phonenum: "555-3535",
    hangout: "High Tide Beach",
    sport: "Surfing",
    food: "null",
    clothing: "Anything Yellow",
  },
  {
    name: "Mike",
    phonenum: "555-2226",
    hangout: "High Tide Beach",
    sport: "Surfing",
    food: "null",
    clothing: "Hat",
  },
  {
    name: "Scott",
    phonenum: "555-5599",
    hangout: "Jim's Gym",
    sport: "Basketball",
    food: "null",
    clothing: "Anything Yellow",
  },
  {
    name: "Bob",
    phonenum: "555-4884",
    hangout: "Jim's Gym",
    sport: "Basketball",
    food: "null",
    clothing: "Glasses",
  },
  {
    name: "Carlos",
    phonenum: "555-6668",
    hangout: "Jim's Gym",
    sport: "Tennis",
    food: "null",
    clothing: "Hat",
  },
  {
    name: "Matt",
    phonenum: "555-7557",
    hangout: "Jim's Gym",
    sport: "Tennis",
    food: "null",
    clothing: "Glasses",
  },
];

export const card_list = items.map(
  (r) => new Card(r.name, r.phonenum, r.hangout, r.sport, r.food, r.clothing)
);
